Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 200
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
